data:
  image: cogniteev/echo
  volumes:
   - /var/www/config
   - /var/lib/mysql

db:
  image: mariadb:latest
  ports:
   - "3306:3306"
  volumes_from:
   - data
  environment:
   - MYSQL_ROOT_PASSWORD=test
   - MYSQL_USER=esotalk
   - MYSQL_PASSWORD=test
   - MYSQL_DATABASE=esotalk

web:
  build: .
  links:
   - db
  ports:
   - "80:80"
  volumes_from:
   - data
  environment:
   - DB_USER=esotalk
   - DB_PASSWORD=test
   - DB_NAME=esotalk